CREATE TABLE IF NOT EXISTS USERS (
  id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  login VARCHAR(30) NOT NULL,
  real_name VARCHAR(255),
  pass VARCHAR(64) NOT NULL,
  salt VARCHAR(4) NOT NULL,
  money INT(32) UNSIGNED NOT NULL,
  worker BOOLEAN NOT NULL,
  system BOOLEAN NOT NULL,
  PRIMARY KEY  (id),
  UNIQUE (login)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

insert into USERS 
  (login, real_name, pass, salt, money, worker, system) 
VALUES 
  ("SYSTEM", "", "", "", 0, 0, 1),
  ("RESERVED", "", "", "", 0, 0, 1);

CREATE TABLE IF NOT EXISTS SESSIONS (
  user_id INT(32) UNSIGNED NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  started TIMESTAMP NOT NULL,
  active BOOLEAN NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS ORDERS (
  id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  summary VARCHAR(64) NOT NULL,
  description TEXT NOT NULL,
  creator INT(32) UNSIGNED NOT NULL,
  executor INT(32) UNSIGNED,
  cost INT(32) UNSIGNED NOT NULL,
  created TIMESTAMP NOT NULL,
  paid BOOLEAN NOT NULL,
  completed BOOLEAN NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS TRANSFERS (
  id INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  from_id INT(32) UNSIGNED NOT NULL,
  to_id INT(32) UNSIGNED NOT NULL,
  amount INT(32) UNSIGNED NOT NULL,
  started TIMESTAMP NOT NULL,
  context_id INT(32) UNSIGNED NOT NULL,
  completed BOOLEAN NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;